spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/p2pBank?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # (or create-drop during dev)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true  # ???? SQL ?? ??

  sql:
    init:
      mode: always  # ???? ?? ??

jwt:
  secret: asjdklfajskldgjlk1j23lk1j5ut893uaww98erun9813uvn49

nhapi:
  base-uri: "https://developers.nonghyup.com"
  iscd: "002833"
  accessToken: "8e6fbc14e07a31d2eb3cbdcda7315d04dc360a285b939f74af56b99d8f4b51a3"

aes:
  secret-key: "12345678901234567890123456789012"
