spring:
  data:
    redis:
      host: p2pbank-redis
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/p2pBank?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create  # (or create-drop during dev)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true  # ???? SQL ?? ??

  sql:
    init:
      mode: always  # ???? ?? ??

jwt:
  secret: asjdklfajskldgjlk1j23lk1j5ut893uaww98erun9813uvn49
